# Prefix in chat
chatPrefix: HorseKeep
# Default horse protection limit by player
horsesDefaultLimit: 3
# Disable horse damage from mobs & environment (fall, suffocation...)
disableHorseEnvironmentalDamage: true
# Disable horse damage from any player
disableHorseDamage: false
# Disable horse damage from horse members and owner
disableHorseDamageFromMembers: true
# Used for setting default identifier to horses **don't change this**
internalIncrementalIdentifier: 1
# Auto-tame wild horse on protect ?
autoTameHorseOnProtect: false
# Enable Metrics (statistics)
enableMetric: true
# Custom horse protection limit, with permission horsekeep.groups.<group-name>
groups:
  - vip: 5
  - staff: 10